import fs from 'fs';
import path from 'path';

const RAW_DATA_PATH = 'C:/Users/iagui/AI Projects/Repos de GitHub/proyectos-sonepar/app/sonepar-catalog-scraper/catalogo-final-sonepar.json';
const OUTPUT_PATH = 'C:/Users/iagui/AI Projects/Repos de GitHub/proyectos-sonepar/app/src/data/catalogoSonepar.js';

function transform() {
  console.log('--- Transform Catalog Script ---');
  console.log('Loading raw data from:', RAW_DATA_PATH);
  
  if (!fs.existsSync(RAW_DATA_PATH)) {
    console.error('Error: Raw data file not found at', RAW_DATA_PATH);
    process.exit(1);
  }

  const rawData = JSON.parse(fs.readFileSync(RAW_DATA_PATH, 'utf8'));
  console.log(`Loaded ${rawData.length} products.`);

  // We write the file with CATALOGO_PLANO and then initialize the other exports
  // to save file size while maintaining structured, fast-access data.
  
  console.log('Generating JS file content...');
  
  const outputContent = `/**
 * CATALOGO SONEPAR - DATA SOURCE
 * This file is automatically generated by app/scripts/transformCatalog.mjs
 * Generated at: ${new Date().toISOString()}
 */

// Raw flat data
export const CATALOGO_PLANO = ${JSON.stringify(rawData)};

// Pre-computed Index by reference (populated at runtime to save file size)
export const INDEX_REFERENCIAS = {};

// Pre-computed Hierarchy by familia and gama (populated at runtime to save file size)
export const CATALOGO_JERARQUICO = {};

console.time('Catalog Initialization');

// Initialize indices from CATALOGO_PLANO
CATALOGO_PLANO.forEach(product => {
  const { ref, familia, subfamilia } = product;
  
  // Index by Reference
  if (ref) {
    INDEX_REFERENCIAS[ref] = product;
  }
  
  // Hierarchy: Familia -> Gama (Subfamilia)
  const famKey = familia || 'SIN_FAMILIA';
  if (!CATALOGO_JERARQUICO[famKey]) {
    CATALOGO_JERARQUICO[famKey] = {};
  }
  
  const gama = subfamilia || 'OTRAS_GAMAS';
  if (!CATALOGO_JERARQUICO[famKey][gama]) {
    CATALOGO_JERARQUICO[famKey][gama] = [];
  }
  
  CATALOGO_JERARQUICO[famKey][gama].push(product);
});

console.timeEnd('Catalog Initialization');

/**
 * Returns subcategories (gamas) for a given category (familia).
 * Optionally filters by brand.
 */
export const getGamasPorMarcaYCategoria = (marca, categoria) => {
  if (!CATALOGO_JERARQUICO[categoria]) return [];
  
  const gamas = Object.keys(CATALOGO_JERARQUICO[categoria]);
  
  if (!marca || marca === 'TODAS' || marca === '') {
    return gamas.sort();
  }
  
  // If filtered by brand, only return gamas that have products from that brand
  return gamas
    .filter(gama => CATALOGO_JERARQUICO[categoria][gama].some(p => p.marca === marca))
    .sort();
};

/**
 * Helper to get products by family and gama
 */
export const getProductosPorGama = (familia, gama) => {
  if (!CATALOGO_JERARQUICO[familia]) return [];
  return CATALOGO_JERARQUICO[familia][gama] || [];
};

/**
 * Helper to get product by reference
 */
export const getProductoPorRef = (ref) => {
  return INDEX_REFERENCIAS[ref] || null;
};

/**
 * Returns all unique brands in the catalog or in a specific family
 */
export const getMarcas = (familia = null) => {
  const products = familia ? 
    Object.values(CATALOGO_JERARQUICO[familia] || {}).flat() : 
    CATALOGO_PLANO;
    
  const marcas = new Set(products.map(p => p.marca).filter(Boolean));
  return Array.from(marcas).sort();
};
`;

  console.log(`Writing output to: ${OUTPUT_PATH}...`);
  fs.writeFileSync(OUTPUT_PATH, outputContent);
  
  const stats = fs.statSync(OUTPUT_PATH);
  console.log(`Success! Final file size: ${(stats.size / 1024 / 1024).toFixed(2)} MB`);
}

try {
  transform();
} catch (error) {
  console.error('Fatal error during transformation:', error);
  process.exit(1);
}
